### PR TITLE
[Imprint] Enable Nextcloud 12 support

### PR DESCRIPTION
**Pull request by MichaIng**
Added Nextcloud version string to enable Nextcloud support until version 12.

### CODE REVIEW

**Comment by MariusBluem** [comment]
Have you tested the app?

**Comment by MichaIng** [comment]
I refer to this github issue https://github.com/nextcloud/server/issues/5626
and this forum thread https://help.nextcloud.com/t/integrate-legal-privacy-info/14293/12?u=michaing
where another user tested it successfully. Since the commit is trivial, I did not test it by myself so far, will do that the later evening.

**Comment by blu-IT** [comment]
Well, I can confirm that modifing the app as mentioned above works for a NC 12 installation, but the settings made in the administration area (Administration -> Additional settings -> Imprint) are not displayed when returning to that page/settings.
The imprint section configured with the text is still displayed above, but remains empty in the administrstion area. I think this is confuesing, because you could think that imprint is not configured.

**Comment by blu-IT** [comment]
OK, I also tried with "external" module now - it doesn't work at all (?!). No site is shown, when clicking the button.
So for the moment, it's still better for me (personally), to go on with the imprint app and the little bug.
What I also like very much and I think it is very _important_: When using imprint, **the imprint is also shown when you are not logged in inside the NC instance**.

**Comment by MariusBluem** [comment]
If you have trouble using external please file a bug report in the external-repo. It’s working for me and was improved in the last weeks a lot ✊️

If the imprint-app works for you, please patch it on your instance by yourself. Meging it here would suggest that this app is developed/tested with v12 which it is *not*, since there is a huge bug, which would cause bug reports. Another solution would be to fix the bugs it has ...

I hope you understand that simply merging this would definitely not meet our high standards for quality and stability. But feel free to go on developing this ;)

**Comment by LukasReschke** [comment]
Closing due to the reasons pointed out by @MariusBluem.

**Comment by MichaIng** [comment]
Just to do a start/reminder in fixing imprint, this is shown by browser console when opening admin / additional settings:
```
Uncaught TypeError: Cannot read property 'ownerDocument' of null
    at Function.ga.contains (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:2)
    at Function.buildFragment (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:3)
    at a.fn.init.domManip (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:3)
    at a.fn.init.append (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:3)
    at a.fn.init.<anonymous> (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:3)
    at n.access (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:2)
    at a.fn.init.html (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:3)
    at Object.success (settings.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:67)
    at j (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:2)
    at Object.fireWith [as resolveWith] (core.js?v=201af79b5e0bfcd4e8e8a3e0a4114d2b:2)

  | ga.contains | @ | core.js?v=201af79…:2
  | buildFragment | @ | core.js?v=201af79…:3
  | domManip | @ | core.js?v=201af79…:3
  | append | @ | core.js?v=201af79…:3
  | (anonymous) | @ | core.js?v=201af79…:3
  | n.access | @ | core.js?v=201af79…:2
  | html | @ | core.js?v=201af79…:3
  | (anonymous) | @ | settings.js?v=201af79…:67
  | j | @ | core.js?v=201af79…:2
  | fireWith | @ | core.js?v=201af79…:2
  | x | @ | core.js?v=201af79…:4
  | (anonymous) | @ | core.js?v=201af79…:4
  | XMLHttpRequest.send (async) |   |  
  | send | @ | core.js?v=201af79…:4
  | ajax | @ | core.js?v=201af79…:4
  | _call | @ | merged-template-prepend.js?v=201af79…:4093
  | getValue | @ | merged-template-prepend.js?v=201af79…:4137
  | getValue | @ | merged-template-prepend.js?v=201af79…:4201
  | (anonymous) | @ | settings.js?v=201af79…:66
  | j | @ | core.js?v=201af79…:2
  | fireWith | @ | core.js?v=201af79…:2
  | ready | @ | core.js?v=201af79…:2
  | I | @ | core.js?v=201af79…:2
```

`core.js` is `nextcloud/core/vendor/core.js`
`settings.js` is `nextcloud/apps/imprint/js/settings.js`

**Pull request closed without merging**
