### PR TITLE
Remove old apps

### PR DESCRIPTION
**Pull request by MariusBluem**
* **emoji** (removed due native support in Nextcloud)
* **files_videoviewer** (moved over to files_videoplayer)
* **imprint** (moved to external & theming-app)
* **ownpad_lite** (moved to ownpad community app & replaced by other notes-apps)
* **pushnotifications** (is now integrated with other code)
* **reader** (replaced by collabora, onlyoffice & documents - no development here)
* **tattoo** (theming, unsplash, theming_customcss)
* **user_persona** (persona was shut down by Mozilla in 2016)
* **user_saml** (new app in separate repository)

Signed-off-by: Marius Blüm <marius@lineone.io>

### CODE REVIEW

**Comment by jancborchardt** [comment]
@MorrisJobke @rullzer what do you think?

**Comment by jancborchardt** [comment]
Btw, only `user_external` is not older than 2 years and that people contribute to. Should we move that one to a separate repository – then it doesn’t create the illusion any of these other apps are still maintained.

What do you think @MorrisJobke @rullzer?

**Comment by MorrisJobke** [comment]
> Btw, only `user_external` is not older than 2 years and that people contribute to.

This is also fairy unmaintained. It is used by some people, but mostly only gets a version bump and not much testing. :(

**Comment by jancborchardt** [comment]
Yes, but separating that one semi-maintained app out and adding all the people to the repository would already be much better than having it rot in here. ;)

Contributors to the user_external app [from the history](https://github.com/nextcloud/apps/commits/master/user_external) are @tflidd @umgfoin @pierreozoux @MarvAmBass @kosli – if they would like to be maintainers we could simply do that. :slightly_smiling_face: 

Or is it not intended to support the app further as there is a replacement?

**Comment by MorrisJobke** [comment]
Fine with me to extract it

**Comment by violoncelloch** [comment]
@jancborchardt thank you for inviting me to be co-maintainer of user_external! I will think about it, but would need some more information on what it would mean exactly to be co-maintainer of the app...?

**Comment by jancborchardt** [comment]
@violoncelloch nothing more than you are comfortable with. :) Just making sure that fixes and pull requests other people make get merged, adjusted or you @-mention the right people, and that also it just gets upped for every new version. :) That’s the basics.

**Comment by violoncelloch** [comment]
That sounds doable :) I think you can count me in...
For the @-mentions I think I still need to learn who is the right person for what, but that will come over time.

**Comment by pierreozoux** [comment]
Yes we still use IMAP for our user login, and happy to see somebody to step in as maintainer. We plan to switch to either saml or ldap in 2019. But yeah, we don't have enough php compétences to pretend to maintain it. And little financial resources to support :/

**Comment by jancborchardt** [comment]
@violoncelloCH there you go, I created https://github.com/nextcloud/user_external for the app. :) Also the group @nextcloud/user_external where I added the people who contributed to it in the past whom I mentioned above.

Let me know if that works or any further permissions are needed. :) @MorrisJobke @rullzer do we have some sort of best practice to move this app out of this big repository into its own? I guess there’s no way to preserve history so probably @violoncelloCH initially just copypastes it, correct?

**Comment by MariusBluem** [comment]
Could we then unbundle this app from the release binary and just move it into the app store - I mean: it is not usable with 15.0.0 for now anyway so we would not break something? 🤔

**Comment by violoncelloCH** [comment]
Is the history preserved if we move files inside a repo? If so, could copy/clone the whole repo and then remove all other apps and move user_external to the root...?

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/apps/pull/69#issuecomment-448937195

**Comment by MorrisJobke** [comment]
> Let me know if that works or any further permissions are needed. :) @MorrisJobke @rullzer do we have some sort of best practice to move this app out of this big repository into its own? I guess there’s no way to preserve history so probably @violoncelloCH initially just copypastes it, correct?

There is a git command to do this. It extracts the history of a sub directory. Just search for it in the internet. 😉

**Comment by violoncelloCH** [comment]
@MorrisJobke I found two ways to do it: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ (uses `git filter-branch --prune-empty --subdirectory-filter`) and https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository/17864475#17864475 (uses `git subtree split`). Which is the correct (/better) way to do it?

**Comment by jancborchardt** [comment]
@violoncelloCH maybe try both locally and see which one works better? Important thing to look for would also be that the repository size is not as big as the whole apps repo. :)

**Comment by violoncelloCH** [comment]
`git filter-branch` seems to work fine. Repo size 304K out of 420 MB for the apps repo. Only the master branch is kept.

**Comment by jancborchardt** [comment]
@violoncelloCH good stuff! Let me know if pushing to the new repo works fine or if you need anything! Thanks so much for taking care of this! :)

**Comment by violoncelloCH** [comment]
@jancborchardt pushing worked! hope it's all fine...
I think we need to turn on branch protection for master now? Can you do this? I don't have access to the repo settings...

**Comment by jancborchardt** [comment]
@violoncelloCH done! :) Let’s continue in the repository then! :)

**Pull request merged**
