### PR TITLE
Add SSH password authentication to user_external

### PR DESCRIPTION
**Pull request by davefullard**
I had a basic requirement to authenticate against an existing SSH server, saving me the requirement to open up yet another port on the firewall to allow SMB traffic (my only other way of external authentication), this is the result. Short, sweet and very basic.

### CODE REVIEW

**Comment by violoncelloCH** [comment]
Hi, thank you for your contribution! 
Since we moved user_external to it's dedicated repository at https://github.com/nextcloud/user_external (I'm one of the new maintainers) could you please reopen your PR there?

**Comment by jancborchardt** [comment]
@violoncelloCH @DavieDavieDave is this meanwhile applied at the new repository? :) If not please do, as we want to archive this repository at some point.

**Comment by violoncelloCH** [comment]
@jancborchardt no this hasn't been applied at the new repo... there is no way to move PRs isn't it? What's the best approach to go for here?

**Comment by jancborchardt** [comment]
Same here as in the other pull request, it's unfortunately not possible to move pull requests. Since it's been some months, I'd recommend you manually apply it and credit @DavieDavieDave in the commit message. :)

**Pull request closed without merging**
