### PR TITLE
add warning about app move to new repo

### PR DESCRIPTION
**Pull request by violoncelloCH**
cc @nextcloud/user_external 

Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Comment by MariusBluem** [comment]
I‘d say we remove the code and add this note to the main README.md 🙈

**Comment by violoncelloCH** [comment]
The current version still links here, that's why I would add this and remove the code once 14 is EOL... what do you think?

**Comment by MariusBluem** [comment]
Since it is shipped the link does appear nowhere (outside of the code). But okay - this should be fine.

**Comment by violoncelloCH** [comment]
The link (at least for me on a production setup) shows up in the app management in the sidebar:
image
(as `Visit Website ↗`)

**Comment by MariusBluem** [comment]
Ah ... mixed up shipped and force enabled apps (like files or dav which you cannot disable from webui)

**Pull request merged**
