### PR TITLE
user_external bump to 15

### PR DESCRIPTION
**Pull request by skjnldsv**
fixes nextcloud/server#12506

### CODE REVIEW

**Comment by violoncelloch** [comment]
@skjnldsv sign-off missing on the commit? If I'm right the check is failing because of that.

**Comment by violoncelloch** [comment]
As I've described in https://github.com/nextcloud/server/issues/12506#issuecomment-447333022, I manually changed the `max-version` in a live installation during the update process which led to an unhandled OCP\AutoloadNotAllowedException. Moving `user_external` away and back into `apps/` and disabling/enabling multiple times solved this. I also had to change the `max-version` to 15 again, because it was somehow overwritten back to 14. I hope that was only a problem because I was already in the upgrade process while changing the `max-version`. If so these changes here should be sufficient.

**Comment by violoncelloch** [comment]
also, will this be part of 15.0.1 or do we have a possibility to put it in a new build of 15.0.0 to prevent other people from recieving the same error during updating?

**Comment by MariusBluem** [comment]
> also, will this be part of 15.0.1 or do we have a possibility to put it in a new build of 15.0.0 to prevent other people from recieving the same error during updating?

`15.0.1` should be fine :)

**Comment by MariusBluem** [comment]
We could also ship this as an Independent app update via our appstore, as we did it for hotfixes with `files_pdfviewer`

**Comment by violoncelloCH** [comment]
@MariusBluem if we extract user_external in a seperated repo as proposed here https://github.com/nextcloud/apps/pull/59#issuecomment-443725291 by @jancborchardt and if I'll be a new co-maintainer of this app I could probably do the appstore release...

**Comment by MariusBluem** [comment]
> @MariusBluem if we extract user_external in a seperated repo as proposed here #59 (comment) by @jancborchardt and if I'll be a new co-maintainer of this app I could probably do the appstore release if you want...

@jancborchardt @violoncelloCH Just to inform you: I have transferred all issues from /apps/ to /user_external/ ... So we will continue there to track everything. Code is still here - I think the best thing would be to move this simply by downloading and importing - don't think we will hardly miss that git history 🤔

**Comment by nickvergessen** [comment]
We can also copy the repo code over and removr all other apps from there...

But i would let morris do that because the release script needs adjustments

**Comment by violoncelloCH** [comment]
@MariusBluem : thank you for moving the issues!

> We can also copy the repo code over and removr all other apps from there...

@nickvergessen & @MariusBluem : @MorrisJobke suggested to use a way to preserve the history in https://github.com/nextcloud/apps/pull/59#issuecomment-448942054

@MorrisJobke : Am I right that we will first move/copy the app to the new repo and then detach it from the server release and publish it to the appstore?

@skjnldsv : could we get in this PR as soon as possible so I can start moving the code to the new repo? Or is there a way to move PRs as well @MariusBluem?

**Comment by skjnldsv** [comment]
As you wish :stars:

**Pull request merged**
