### PR TITLE
Add possibility to login with email on imap

### LINKED ISSUE #40: IMAP: Restrict domain in existing install -> new users created, not using existing ones
### Affected apps
user_external

### Steps to reproduce
1. Activate user_external, add to config.php:
```
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{localhost:993/imap/ssl/novalidate-cert}',
      ),
    ),
  ),

```
(NOTICE: NO Domain Restriction!!)

2. Login with a valid IMAP Mail Adress (user@example.com)
3. User is created as "user@example.com" (verified by logging in as an NC Admin)
4. Put some Data in Nextcloud
5. Log Off
6. Decide to restrict access to domain "example.com" only, so change config.php:
```
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{localhost:993/imap/ssl/novalidate-cert}', 'example.com'
      ),
    ),
  ),

```
(NOTICE: Domain "example.com" added to array)

7. Again login with the valid IMAP User "user@example.com"
8. The first login wizard appears, so the user seems to be a new one. Indeed the data from step 4 is away.
9. Login as NC Admin, notice there are now two users: "user" and "user@example.com"
10. Change back the config.php not to restrict to "example.com"
11. Login as "user@example.com"
12. The data from step 4 is available again.

The behaviour of user_external is as documented; when restricted to a domain, the domain part is stripped while creating the new user, so the username is just "user".
This is quite fine for fresh installations. 
But in existing installations, when this option wasn't initially set in config.php and setting it later (for whatever reason), existing users can't access their data any more.

Can't there be an option for this, speaking, not to strip the domain part but restrict to a domain? This won't break existing installations, when one decides to activate domain restrictions later.
Or could the app check, if there already are users with this domain part and use them further?

**Server version:** (see your admin page)
12.0.3

### PR DESCRIPTION
**Pull request by pierreozoux**
Fixes #40 

It is my first php/Nextcloud PR, so be gentle :)

If you think we should put this behind an option, let me know.
Also, you have to keep in mind that this will create an entry in user_external, but you'll still have to delete manually the uid in user entry if you are migrating from normal user to imap user (in reference to #34).

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Makes sense. Sadly I cannot test this. 

cc @rullzer and @icewind1991 for some feedback on this as well.

**Comment by rullzer** [comment]
Yes makes sense. but also I have no easy way to test this quickly.

**Comment by pierreozoux** [comment]
Do you think we could get this merged before Nc13 is released?

Thanks a lot!

**Comment by umgfoin** [comment]
@MorrisJobke 
As NC 13 release is approaching: Could somebody add a bug-label, here, otherwise [commit f8fb4d9 ](https://github.com/nextcloud/apps/commit/f8fb4d98464254c037b330d4a17c9851b7bee823) will pass into stable breaking an official app in NC13 on Postgres.

Thanks,
umgfoin.

**Comment by MorrisJobke** [comment]
> As NC 13 release is approaching: Could somebody add a bug-label, here, otherwise commit f8fb4d9 will pass into stable breaking an official app in NC13 on Postgres.

🙈 Nobody really maintains this. And I totally have overseen that this is in our release :/

@rullzer @nickvergessen @icewind1991 Ideas?

**Comment by umgfoin** [comment]
> Nobody really maintains this. 

No worries, nearly maintenance-free, sofar ;-)
[PR pending - review required](https://github.com/nextcloud/apps/pull/47).

++umgfoin.

**Pull request merged**
